candidat_index:
    path:     candidat/
    defaults: { _controller: "AppBundle:gestion/Candidat:index" }
    methods:  GET

candidat_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:gestion/Candidat:show" }
    methods:  GET

candidat_new:
    path:     /new
    defaults: { _controller: "AppBundle:gestion/Candidat:new" }
    methods:  [GET, POST]

candidat_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:gestion/Candidat:edit" }
    methods:  [GET, POST]

candidat_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:gestion/Candidat:delete" }
