parti_index:
    path:     /
    defaults: { _controller: "AppBundle:gestion/Parti:index" }
    methods:  GET

parti_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:gestion/Parti:show" }
    methods:  GET

parti_new:
    path:     /new
    defaults: { _controller: "AppBundle:gestion/Parti:new" }
    methods:  [GET, POST]

parti_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:gestion/Parti:edit" }
    methods:  [GET, POST]

parti_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:gestion/Parti:delete" }
    methods:  DELETE



parti_RemoveAll:
    path:     /removeAll
    defaults: { _controller: "AppBundle:gestion/Parti:removeAll" }