townHall_index:
    path:     /
    defaults: { _controller: "AppBundle:gestion/TownHall:index" }
    methods:  GET

townHall_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:gestion/TownHall:show" }
    methods:  GET

townHall_new:
    path:     /new
    defaults: { _controller: "AppBundle:gestion/TownHall:new" }
    methods:  [GET, POST]

townHall_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:gestion/TownHall:edit" }
    methods:  [GET, POST]

townHall_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:gestion/TownHall:delete" }
    methods:  DELETE
