<?php

namespace AppBundle\Repository;

/**
 * DeskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeskRepository extends \Doctrine\ORM\EntityRepository
{
}
