<?php

namespace AppBundle\Repository;

/**
 * DetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailElectionDeskRepository extends \Doctrine\ORM\EntityRepository
{
}
