<?php

namespace AppBundle\Repository;

/**
 * DetailElectionTownHallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailElectionTownHallRepository extends \Doctrine\ORM\EntityRepository
{

}
