<?php

namespace AppBundle\Repository;

/**
 * MetaElectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetaElectionRepository extends \Doctrine\ORM\EntityRepository
{
}
