<?php

namespace AppBundle\Repository;

/**
 * PackVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PackVoteTmpRepository extends \Doctrine\ORM\EntityRepository
{
}
