<?php

namespace AppBundle\Repository;

/**
 * PackHundredRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PackHundredRepository extends \Doctrine\ORM\EntityRepository
{
}
