<?php

namespace AppBundle\Repository;

/**
 * PackHoraireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PackHoraireRepository extends \Doctrine\ORM\EntityRepository
{
}
