<?php

namespace AppBundle\Repository;

/**
 * PartiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartiRepository extends \Doctrine\ORM\EntityRepository
{
}
