<?php

namespace AppBundle\Repository;

/**
 * QgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QgRepository extends \Doctrine\ORM\EntityRepository
{
}
