<?php

namespace AppBundle\Repository;

/**
 * TownHallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TownHallRepository extends \Doctrine\ORM\EntityRepository
{
}
