<?php

use Symfony\Component\Routing\RequestContext;
use Symfony\Component\Routing\Exception\RouteNotFoundException;
use Psr\Log\LoggerInterface;

/**
 * appProdDebugProjectContainerUrlGenerator
 *
 * This class has been auto-generated
 * by the Symfony Routing Component.
 */
class appProdDebugProjectContainerUrlGenerator extends Symfony\Component\Routing\Generator\UrlGenerator
{
    private static $declaredRoutes;

    /**
     * Constructor.
     */
    public function __construct(RequestContext $context, LoggerInterface $logger = null)
    {
        $this->context = $context;
        $this->logger = $logger;
        if (null === self::$declaredRoutes) {
            self::$declaredRoutes = array(
        'candidat_index' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\CandidatController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/gestion/candidat/',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'candidat_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\CandidatController::showAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/gestion/candidat',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'candidat_new' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\CandidatController::newAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/gestion/candidat/new',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'candidat_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\CandidatController::editAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/gestion/candidat',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'candidat_delete' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\CandidatController::deleteAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/delete',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/gestion/candidat',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'mairie_index' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\MairieController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/gestion/mairie/',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'mairie_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\MairieController::showAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/gestion/mairie',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'mairie_new' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\MairieController::newAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/gestion/mairie/new',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'mairie_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\MairieController::editAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/gestion/mairie',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'mairie_delete' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\MairieController::deleteAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/delete',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/gestion/mairie',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'election_index' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\ElectionController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/gestion/election/',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'election_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\ElectionController::showAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/gestion/election',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'election_new' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\ElectionController::newAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/gestion/election/new',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'election_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\ElectionController::editAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/gestion/election',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'election_delete' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\ElectionController::deleteAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/delete',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/gestion/election',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'qg_index' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\QgController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/gestion/qg/',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'qg_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\QgController::showAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/gestion/qg',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'qg_new' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\QgController::newAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/gestion/qg/new/',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'qg_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\QgController::editAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/gestion/qg',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'qg_delete' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\QgController::deleteAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/delete',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/gestion/qg',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'bureau_index' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\BureauController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/gestion/bureau/',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'bureau_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\BureauController::showAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/gestion/bureau',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'bureau_new' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\BureauController::newAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/gestion/bureau/new',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'bureau_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\BureauController::editAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/gestion/bureau',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'bureau_delete' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\BureauController::deleteAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/delete',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/gestion/bureau',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'packvote_index' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\PackVoteController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/gestion/vote/',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'packvote_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\PackVoteController::showAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/gestion/vote',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'packvote_new' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\PackVoteController::newbisAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    1 =>     array (      0 => 'text',      1 => '/gestion/vote/new',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'packvote_new_election' => array (  0 =>   array (    0 => 'bureau',    1 => 'election',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\PackVoteController::newElectionsAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'election',    ),    1 =>     array (      0 => 'text',      1 => '/election',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'bureau',    ),    3 =>     array (      0 => 'text',      1 => '/gestion/vote/new',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'packvote_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\PackVoteController::editAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/gestion/vote',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'packvote_delete' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\PackVoteController::deleteAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/delete',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/gestion/vote',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'packvote_deleteAllUltime' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\PackVoteController::remiseZeroPackVoteUltimeAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/gestion/vote/deleteAllUltime',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'bureau_candidatPlus' => array (  0 =>   array (    0 => 'bureau',    1 => 'election',    2 => 'candidat',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\utilisation\\BureauController::votePlusAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'candidat',    ),    1 =>     array (      0 => 'text',      1 => '/candidat',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'election',    ),    3 =>     array (      0 => 'text',      1 => '/election',    ),    4 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'bureau',    ),    5 =>     array (      0 => 'text',      1 => '/bureau/candidatPlus/bureau',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'bureau_candidatMoins' => array (  0 =>   array (    0 => 'bureau',    1 => 'election',    2 => 'candidat',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\utilisation\\BureauController::voteMoinsAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'candidat',    ),    1 =>     array (      0 => 'text',      1 => '/candidat',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'election',    ),    3 =>     array (      0 => 'text',      1 => '/election',    ),    4 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'bureau',    ),    5 =>     array (      0 => 'text',      1 => '/bureau/candidatMoins/bureau',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'bureau_exportCsv' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\utilisation\\BureauController::csvAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    1 =>     array (      0 => 'text',      1 => '/bureau/csv',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'bureau_utilisation_index' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\utilisation\\BureauController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/bureau/',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'bureau_utilisation_index_bureau' => array (  0 =>   array (    0 => 'bureau',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\utilisation\\BureauController::indexAvecBureauAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'bureau',    ),    1 =>     array (      0 => 'text',      1 => '/bureau',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'qg_utilisation_index' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\utilisation\\QgController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    1 =>     array (      0 => 'text',      1 => '/qg',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'qg_utilisation_definirip' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'AppBundle:Qg:setNewIp',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    1 =>     array (      0 => 'text',      1 => '/qg/setNewIp',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'qg_utilisation_killall' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'AppBundle:Qg:killall',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    1 =>     array (      0 => 'text',      1 => '/qg/killall',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'qg_utilisation_delAllBureau' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'AppBundle:Qg:remiseZeroBureau',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    1 =>     array (      0 => 'text',      1 => '/qg/delAllBureau',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'mairie_utilisation_index' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\utilisation\\MairieController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/mairie/',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'mairie_utilisation_killall' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\utilisation\\MairieController::killallAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/mairie/killall',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'mairie_utilisation_delAllBureau' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\utilisation\\MairieController::remiseZeroBureauAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/mairie/delAllBureau',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'utilisation_packhoraire_getlast' => array (  0 =>   array (    0 => 'bureau',    1 => 'election',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\utilisation\\PackHoraireController::getLastParticipationAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/getLast',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'election',    ),    2 =>     array (      0 => 'text',      1 => '/election',    ),    3 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'bureau',    ),    4 =>     array (      0 => 'text',      1 => '/utilisation/packhoraire/bureau',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'utilisation_packhoraire_voirgraph' => array (  0 =>   array (    0 => 'mairie',    1 => 'election',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\utilisation\\PackHoraireController::voirGraphParticipationAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'election',    ),    1 =>     array (      0 => 'text',      1 => '/election',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'mairie',    ),    3 =>     array (      0 => 'text',      1 => '/utilisation/packhoraire/voirgraph/mairie',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'utilisation_packhoraire_getfileparticipation' => array (  0 =>   array (    0 => 'mairie',    1 => 'election',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\utilisation\\PackHoraireController::getFileParticipationAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'election',    ),    1 =>     array (      0 => 'text',      1 => '/election',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'mairie',    ),    3 =>     array (      0 => 'text',      1 => '/utilisation/packhoraire/getfileparticipation/mairie',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'packhoraire_index' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\PackHoraireController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/gestion/packhoraire/',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'packhoraire_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\PackHoraireController::showAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/gestion/packhoraire',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'packhoraire_new' => array (  0 =>   array (    0 => 'bureau',    1 => 'election',    2 => 'nb',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\PackHoraireController::newBisAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'nb',    ),    1 =>     array (      0 => 'text',      1 => '/nb',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'election',    ),    3 =>     array (      0 => 'text',      1 => '/election',    ),    4 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'bureau',    ),    5 =>     array (      0 => 'text',      1 => '/gestion/packhoraire/bureau',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'packhoraire_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\PackHoraireController::editAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/gestion/packhoraire',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'packhoraire_delete' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\PackHoraireController::deleteAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/delete',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/gestion/packhoraire',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'packhoraire_deleteAll' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\PackHoraireController::remiseZeroPackHoraireAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/gestion/packhoraire/deleteAll',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'packvote_delete_by_bureau' => array (  0 =>   array (    0 => 'bureau',    1 => 'election',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\PackVoteController::remiseZeroPackVoteAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'election',    ),    1 =>     array (      0 => 'text',      1 => '/election',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'bureau',    ),    3 =>     array (      0 => 'text',      1 => '/utilisation/vote/deleteAll/bureau',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'bureau_nbInscrit' => array (  0 =>   array (    0 => 'bureau',    1 => 'election',    2 => 'nbinscrit',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\utilisation\\DetailController::newNbInscritAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'nbinscrit',    ),    1 =>     array (      0 => 'text',      1 => '/nbinscrit',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'election',    ),    3 =>     array (      0 => 'text',      1 => '/election',    ),    4 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'bureau',    ),    5 =>     array (      0 => 'text',      1 => '/utilisation/detail/nbInscrit/bureau',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'visiteur_index' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\utilisation\\VisiteurRController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/visiteur/',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'visiteur_showVoteDetail' => array (  0 =>   array (    0 => 'mairie',    1 => 'election',    2 => 'mode',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\utilisation\\VisiteurRController::showResultatDetailAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'mode',    ),    1 =>     array (      0 => 'text',      1 => '/mode',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'election',    ),    3 =>     array (      0 => 'text',      1 => '/election',    ),    4 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'mairie',    ),    5 =>     array (      0 => 'text',      1 => '/visiteur/showVoteDetail',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'visiteur_showParticipation' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\utilisation\\VisiteurRController::showParticipationVoteAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/visiteur/showParticipation',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'visiteur_denied' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\utilisation\\VisiteurRController::deniedAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/visiteur/denied',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'parti_index' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\PartiController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/gestion/parti/',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'parti_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\PartiController::showAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/show',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/gestion/parti',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'parti_new' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\PartiController::newAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/gestion/parti/new',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'parti_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\PartiController::editAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/gestion/parti',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'parti_delete' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\gestion\\PartiController::deleteAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/delete',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/gestion/parti',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'utilisation_user_action' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\utilisation\\UserController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/user/actions',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'utilisation_user_possession' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\utilisation\\UserController::possessionAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/user/possession',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'utilisation_user_droits' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\utilisation\\UserController::gererDroitAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/user/role',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'utilisation_user_droits_bureau_ajax' => array (  0 =>   array (    0 => 'user',    1 => 'bureau',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\utilisation\\UserController::gererDroitBureauAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'bureau',    ),    1 =>     array (      0 => 'text',      1 => '/bureau',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'user',    ),    3 =>     array (      0 => 'text',      1 => '/user/role/gererDroit/user',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'utilisation_user_droits_qg_ajax' => array (  0 =>   array (    0 => 'user',    1 => 'qg',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\utilisation\\UserController::gererDroitQgAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'qg',    ),    1 =>     array (      0 => 'text',      1 => '/qg',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'user',    ),    3 =>     array (      0 => 'text',      1 => '/user/role/gererDroit/user',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'utilisation_user_mairie_ajax' => array (  0 =>   array (    0 => 'user',    1 => 'mairie',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\utilisation\\UserController::gererDroitMairieAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'mairie',    ),    1 =>     array (      0 => 'text',      1 => '/mairie',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'user',    ),    3 =>     array (      0 => 'text',      1 => '/user/role/gererDroit/user',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'utilisation_user_droits_bureau_remove_ajax' => array (  0 =>   array (    0 => 'user',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\utilisation\\UserController::enleverDroitBureauAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/bureau',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'user',    ),    2 =>     array (      0 => 'text',      1 => '/user/role/user/gererDroit/remove',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'utilisation_user_droits_qg_remove_ajax' => array (  0 =>   array (    0 => 'user',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\utilisation\\UserController::enleverDroitQgAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/qg',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'user',    ),    2 =>     array (      0 => 'text',      1 => '/user/role/user/gererDroit/remove',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'utilisation_user_droits_mairie_remove_ajax' => array (  0 =>   array (    0 => 'user',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\utilisation\\UserController::enleverDroitMairieAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/mairie',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'user',    ),    2 =>     array (      0 => 'text',      1 => '/user/role/user/gererDroit/remove',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'app_homepage' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\DefaultController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'fos_user_security_login' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'FOS\\UserBundle\\Controller\\SecurityController::loginAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/login',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'fos_user_security_check' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'FOS\\UserBundle\\Controller\\SecurityController::checkAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/login_check',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'fos_user_security_logout' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'FOS\\UserBundle\\Controller\\SecurityController::logoutAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/logout',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'fos_user_profile_show' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'FOS\\UserBundle\\Controller\\ProfileController::showAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/profile/',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'fos_user_profile_edit' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'FOS\\UserBundle\\Controller\\ProfileController::editAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/profile/edit',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'fos_user_registration_register' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'FOS\\UserBundle\\Controller\\RegistrationController::registerAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/register/',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'fos_user_registration_check_email' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'FOS\\UserBundle\\Controller\\RegistrationController::checkEmailAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/register/check-email',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'fos_user_registration_confirm' => array (  0 =>   array (    0 => 'token',  ),  1 =>   array (    '_controller' => 'FOS\\UserBundle\\Controller\\RegistrationController::confirmAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'token',    ),    1 =>     array (      0 => 'text',      1 => '/register/confirm',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'fos_user_registration_confirmed' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'FOS\\UserBundle\\Controller\\RegistrationController::confirmedAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/register/confirmed',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'fos_user_resetting_request' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'FOS\\UserBundle\\Controller\\ResettingController::requestAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/resetting/request',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'fos_user_resetting_send_email' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'FOS\\UserBundle\\Controller\\ResettingController::sendEmailAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/resetting/send-email',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'fos_user_resetting_check_email' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'FOS\\UserBundle\\Controller\\ResettingController::checkEmailAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/resetting/check-email',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'fos_user_resetting_reset' => array (  0 =>   array (    0 => 'token',  ),  1 =>   array (    '_controller' => 'FOS\\UserBundle\\Controller\\ResettingController::resetAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'token',    ),    1 =>     array (      0 => 'text',      1 => '/resetting/reset',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'fos_user_change_password' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'FOS\\UserBundle\\Controller\\ChangePasswordController::changePasswordAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/profile/change-password',    ),  ),  4 =>   array (  ),  5 =>   array (    0 => 'https',  ),),
        'easyadmin' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'JavierEguiluz\\Bundle\\EasyAdminBundle\\Controller\\AdminController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'JavierEguiluz\\Bundle\\EasyAdminBundle\\Controller\\AdminController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
    );
        }
    }

    public function generate($name, $parameters = array(), $referenceType = self::ABSOLUTE_PATH)
    {
        if (!isset(self::$declaredRoutes[$name])) {
            throw new RouteNotFoundException(sprintf('Unable to generate a URL for the named route "%s" as such route does not exist.', $name));
        }

        list($variables, $defaults, $requirements, $tokens, $hostTokens, $requiredSchemes) = self::$declaredRoutes[$name];

        return $this->doGenerate($variables, $defaults, $requirements, $tokens, $parameters, $name, $referenceType, $hostTokens, $requiredSchemes);
    }
}
